export const grapeVarieties = [
    "Albariño",
    "Barbera",
    "Cabernet Sauvignon",
    "Carignan",
    "Chardonnay",
    "Gewürztraminer",
    "Gamay",
    "Grenache",
    "Malbec",
    "Merlot",
    "Moscato",
    "Mourvèdre",
    "Nebbiolo",
    "Petit Verdot",
    "Pinot Noir",
    "Riesling",
    "Sangiovese",
    "Sauvignon Blanc",
    "Syrah",
    "Tempranillo",
    "Torrontés",
    "Vermentino",
    "Viognier",
    "Zinfandel"
]
